const data = {
  products: [
    {
      nombre: 'Estante cromado',
      slug: 'estante-cromado',
      category: 'Estantería',
      image: '/images/estante.jpg',
      price: 120,
      countInStock: 20,
      brand: 'HOD',
      rating: 4.5,
      numReviews: 10,
      description: 'Estante cromado 3 niveles',
    },
    {
      nombre: 'Lona polietileno',
      slug: 'lona-polietileno',
      category: 'Lonas',
      image: '/images/lona.jpg',
      price: 120,
      countInStock: 20,
      brand: 'Aoking',
      rating: 4.5,
      numReviews: 10,
      description: 'Lona polietileno 180g',
    },
    {
      nombre: 'Rodaja placa fija',
      slug: 'rodaja-placa-fija',
      category: 'Rodajas',
      image: '/images/rodaja.jpg',
      price: 120,
      countInStock: 20,
      brand: 'HOD',
      rating: 4.5,
      numReviews: 10,
      description: 'Rodaja placa fija uso pesado',
    },
    {
      nombre: 'Rueda tipo rayo',
      slug: 'rueda-tipo-rayo',
      category: 'Ruedas',
      image: '/images/rueda.jpg',
      price: 120,
      countInStock: 20,
      brand: 'HOD',
      rating: 4.5,
      numReviews: 10,
      description: 'Rueda tipo rayo 9x2',
    },
  ],
};

export default data;
